# This file was generated by GoReleaser. DO NOT EDIT.
cask "paws" do
  name "paws"
  desc ""
  homepage ""
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paws"

  on_macos do
    on_intel do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_amd64.tar.gz"
      sha256 "085697f3eae360e1b47bd15a9c555abc8c689ad0a8d7318e371342705cc32619"
    end
    on_arm do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_arm64.tar.gz"
      sha256 "308a9f50b88721d3fdacda10dad3433eec4000920687d9ae99c23aef216ecb04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_amd64.tar.gz"
      sha256 "948423ca1f060d7761a67b6b5bd842c821aafc874b6dbe62e6a6a9b9706e9f48"
    end
    on_arm do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_arm64.tar.gz"
      sha256 "d5dcd6ccbaf5488869eb9720bb56c6e2b4ce2af881985046af5ebaad3567cc81"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paws"]
    end
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/_paws", "#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  # No zap stanza required
end
