# This file was generated by GoReleaser. DO NOT EDIT.
cask "paws" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "67b384eff04fce4032bf0c5eb8a1f2b821372a0bee86d578a0873d744fb9acf4"
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "651ad220c4867f730d6dd453cef8319d46b146d9dd9640524343eb78fc346f67"
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "554d9ea724873758814a54f61dc305f09eb3e0b6e931adac40dcf32b95bb65a7"
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91c2e6adb4f1294ba378862f2692e5b93850c041404d79da13e054107d97ea70"
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_arm64.tar.gz"
    end
  end

  name "paws"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paws"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paws"]
    end
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/_paws", "#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  # No zap stanza required

end
