# This file was generated by GoReleaser. DO NOT EDIT.
cask "paws" do
  name "paws"
  desc ""
  homepage ""
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paws"

  on_macos do
    on_intel do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_amd64.tar.gz"
      sha256 "b0f37e4f00692a22ecac876491ded499e893f67decae9850a65a141c028ba67f"
    end
    on_arm do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_darwin_arm64.tar.gz"
      sha256 "c7befe714a99b65d1a664341c583db4c2263e3553fb8fc919b1aba76a531138d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_amd64.tar.gz"
      sha256 "10d49677ce421f5e79513be5705c6c33619056d1bab6e48ba2bc370d11d4cbff"
    end
    on_arm do
      url "https://github.com/lzecca78/paws/releases/download/#{version}/paws_#{version}_linux_arm64.tar.gz"
      sha256 "b9cfd5f0a4c6a9fa3f8f300319d6a484e0f3e4df3c7208cf65cad3e9b733d0ad"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paws"]
    end
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/_paws", "#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["#{HOMEBREW_PREFIX}/bin/_paws"]
  end

  # No zap stanza required
end
